"""Generate one YAML per (model x method x budget) into configs/.

The configs are derived, not hand-written: a hand-maintained matrix of ~50
near-identical files drifts, and a drifted config silently changes what a
"budget 0.3 SR-KV run" means halfway through a sweep.

    python scripts/gen_configs.py            # write configs/
    python scripts/gen_configs.py --list     # print the run commands instead
"""

from __future__ import annotations

import argparse
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

MODELS = ["qwen2.5-1.5b", "qwen2.5-0.5b", "llama3.2-3b"]
METHODS = ["full", "streaming_llm", "snapkv_unified", "centroid_merge", "sr_kv"]
BUDGETS = [0.1, 0.2, 0.3, 0.5]
CONTEXT_LENGTHS = [2048, 4096, 8192, 16384]


def config_name(model: str, method: str, budget: float) -> str:
    return f"{model.replace('.', '')}__{method}__b{int(budget * 100):03d}.yaml"


def config_body(model: str, method: str, budget: float) -> str:
    budget_line = "1.0  # the uncompressed reference ignores this" if method == "full" else f"{budget}"
    return f"""# generated by scripts/gen_configs.py - do not edit by hand
model: {model}
method: {method}
budget: {budget_line}
task: niah
context_len: [{", ".join(str(c) for c in CONTEXT_LENGTHS)}]
depths: [0, 25, 50, 75, 100]
n_samples: 3
max_new_tokens: 32
# scoring/structure come from configs/defaults.yaml unless overridden here
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--list", action="store_true", help="print run commands, write nothing")
    parser.add_argument("--outdir", default=str(REPO_ROOT / "configs"))
    args = parser.parse_args()

    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    written = 0
    for model in MODELS:
        for method in METHODS:
            budgets = [1.0] if method == "full" else BUDGETS
            for budget in budgets:
                name = config_name(model, method, budget)
                if args.list:
                    print(f"python eval/run.py --config configs/{name} "
                          f"--output results/{Path(name).stem}.json")
                    continue
                (outdir / name).write_text(config_body(model, method, budget), encoding="utf-8")
                written += 1
    if not args.list:
        print(f"wrote {written} configs to {outdir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
